Controllers/CarrelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bernardi.Luca._5H.Ecommerce.Models;
using Microsoft.AspNetCore.Http;

namespace Bernardi.Luca._5H.Ecommerce.Controllers
{
    public class CarrelloController : Controller
    {
        private readonly dbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CarrelloController(dbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Carrello
        public async Task<IActionResult> Index()
        {
            // Estrai l'ID dell'utente loggato
            int userId = HttpContext.Session.GetInt32("Id") ?? 0;
            
            // Filtra il carrello per l'utente loggato e lo unisce con i prodotti
            var carrello = await _context.Carrello
                .Where(c => c.Utente == userId) // Filtra per l'utente loggato
                .Join(_context.Prodotti, // Unisciti con la tabella dei prodotti
                      c => c.Prodotto, 
                      p => p.Id, 
                      (c, p) => new { Carrello = c, Prodotto = p }) // Seleziona il carrello e il prodotto
                .ToListAsync();

            return View(carrello);
        }

        // GET: Carrello/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrello = await _context.Carrello
                .FirstOrDefaultAsync(m => m.id == id);
            if (carrello == null)
            {
                return NotFound();
            }

            return View(carrello);
        }

        // GET: Carrello/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carrello/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Prodotto,Utente,Quantita")] Carrello carrello)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carrello);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carrello);
        }

        // GET: Carrello/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrello = await _context.Carrello.FindAsync(id);
            if (carrello == null)
            {
                return NotFound();
            }
            return View(carrello);
        }

        // POST: Carrello/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Prodotto,Utente,Quantita")] Carrello carrello)
        {
            if (id != carrello.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carrello);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarrelloExists(carrello.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carrello);
        }

        // GET: Carrello/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrello = await _context.Carrello
                .FirstOrDefaultAsync(m => m.id == id);
            if (carrello == null)
            {
                return NotFound();
            }

            // Ottenere il nome del prodotto associato al carrello
            var prodotto = await _context.Prodotti.FirstOrDefaultAsync(p => p.Id == carrello.Prodotto);
            if (prodotto == null)
            {
                return NotFound();
            }

            // Passare il nome del prodotto alla vista invece dell'ID del prodotto
            ViewData["ProductName"] = prodotto.Name;

            return View(carrello);
        }

        // POST: Carrello/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carrello = await _context.Carrello.FindAsync(id);
            if (carrello != null)
            {
                _context.Carrello.Remove(carrello);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Carrello/DeleteAll
        public async Task<IActionResult> DeleteAll()
        {
            try
            {
                // Ottieni tutti i record nella tabella Carrello
                var carrelloItems = await _context.Carrello.ToListAsync();

                // Rimuovi tutti i record
                _context.Carrello.RemoveRange(carrelloItems);

                // Salva le modifiche nel database
                await _context.SaveChangesAsync();

                // Ritorna alla vista Index o a un'altra vista desiderata
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // Gestisci eventuali eccezioni
                return RedirectToAction("Error", "Home"); // Reindirizza a una vista di errore o gestisci in altro modo
            }
        }

        // POST: Carrello/Ordine66
        [HttpPost]
        public async Task<IActionResult> Ordine66()
        {
            try
            {
                // Estrai l'ID dell'utente loggato
                int userId = HttpContext.Session.GetInt32("Id") ?? 0;

                // Ottieni tutti i record nella tabella Carrello per l'utente loggato
                var carrelloItems = await _context.Carrello
                    .Where(c => c.Utente == userId)
                    .ToListAsync();

                // Rimuovi tutti i record
                _context.Carrello.RemoveRange(carrelloItems);

                // Salva le modifiche nel database
                await _context.SaveChangesAsync();

                // Ritorna alla vista Index o a un'altra vista desiderata
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // Gestisci eventuali eccezioni
                return RedirectToAction("Error", "Home"); // Reindirizza a una vista di errore o gestisci in altro modo
            }
        }

        private bool CarrelloExists(int id)
        {
            return _context.Carrello.Any(e => e.id == id);
        }
    }
}

Controllers/UtentiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bernardi.Luca._5H.Ecommerce.Models;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;

namespace Bernardi.Luca._5H.Ecommerce.Controllers
{
    public class UtentiController : Controller
    {
        private readonly dbContext _context;

        public UtentiController(dbContext context)
        {
            _context = context;
        }
        public IActionResult LogOut()
        {
            string? nickname = HttpContext.Session.GetString("Login");
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult LogIn()
        {
            return View();
        }
         [HttpPost]
        public IActionResult LogIn(Utenti utente)
        {
            // Cerca se esiste l'utente nel DB
            var user = _context.Utenti.FirstOrDefault(u => u.Nickname == utente.Nickname && u.Password == utente.Password);

            if (user != null)
            {
                // L'utente esiste e quindi parte la sessione
                HttpContext.Session.SetString("Login", user.Nickname);
                HttpContext.Session.SetString("IsAdmin", user.Admin.ToString());
                HttpContext.Session.SetInt32("Id", user.Id);

                return RedirectToAction("Index", "Home");
            }

            // Se non va il log in ti rimanda alla stessa pagina
            ModelState.AddModelError(string.Empty, "Invalid Nickname or Password");
            return View(utente);
        }
        // GET: Utenti
        public async Task<IActionResult> Index()
        {
            return View(await _context.Utenti.ToListAsync());
        }

        // GET: Utenti/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utenti = await _context.Utenti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utenti == null)
            {
                return NotFound();
            }

            return View(utenti);
        }

        // GET: Utenti/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Utenti/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cognome,Nickname,DataNascita,Email,Numero,Password,Admin")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utenti);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(LogIn));
            }
            return View(utenti);
        }

        // GET: Utenti/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utenti = await _context.Utenti.FindAsync(id);
            if (utenti == null)
            {
                return NotFound();
            }
            return View(utenti);
        }

        // POST: Utenti/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Cognome,Nickname,DataNascita,Email,Numero,Password,Admin")] Utenti utenti)
        {
            if (id != utenti.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utenti);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtentiExists(utenti.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = utenti.Id });
            }
            return View(utenti);
        }

        // GET: Utenti/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utenti = await _context.Utenti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utenti == null)
            {
                return NotFound();
            }

            return View(utenti);
        }

        // POST: Utenti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var utenti = await _context.Utenti.FindAsync(id);
            if (utenti != null)
            {
                _context.Utenti.Remove(utenti);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool UtentiExists(int id)
        {
            return _context.Utenti.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    string? Valore = HttpContextAccessor?.HttpContext?.Session.GetString("Login");
    string strIsAdmin = HttpContextAccessor?.HttpContext?.Session.GetString("IsAdmin");
    int? Id = HttpContextAccessor?.HttpContext?.Session.GetInt32("Id");
    Boolean IsAdmin = strIsAdmin == "True" ? true : false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bancarella di Nicolas Cage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bernardi.Luca._5H.Ecommerce.styles.css" asp-append-version="true" />
    <style>
        body, 
        .navbar-nav .nav-link, 
        .footer, 
        a.navbar-brand, 
        a.nav-link {
            color: #d2b48c !important;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: #d2b48c;">Bancarella di Nicolas Cage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Prodotti" asp-action="Index">Articoli</a>
                        </li>
                        @{ if (Valore != null)
                           {
                               <li class="nav-item">
                                   <a class="nav-link text-dark" asp-controller="Carrello" asp-action="Index">Carrello</a>
                               </li>
                               if (IsAdmin)
                               {
                                   <li class="nav-item">
                                       <a class="nav-link text-dark" asp-controller="Utenti" asp-action="Details" asp-route-id="@Id">@Valore Admin</a>
                                   </li>
                               }
                               else
                               {
                                   <li class="nav-item">
                                       <a class="nav-link text-dark" asp-controller="Utenti" asp-action="Details" asp-route-id="@Id">@Valore</a>
                                   </li>
                               }
                           }
                           else
                           {
                               <li class="nav-item">
                                   <a class="nav-link text-dark" asp-controller="Utenti" asp-action="LogIn">Accedi</a>
                               </li>
                           }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bancarella di Nicolas Cage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>